// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using Microsoft.EntityFrameworkCore;
using System;
using System.Collections.Generic;
using TradeMonkey.Data.Context.Configurations;
using TradeMonkey.Data.Entity;
#nullable disable

namespace TradeMonkey.Data.Context;

public partial class TmDBContext : DbContext
{
    public TmDBContext(DbContextOptions<TmDBContext> options)
        : base(options)
    {
    }

    public virtual DbSet<CorrelationDatum> CorrelationDatum { get; set; }

    public virtual DbSet<IndicatorDatum> IndicatorDatum { get; set; }

    public virtual DbSet<IndiciesDatum> IndiciesDatum { get; set; }

    public virtual DbSet<PricePredictionDatum> PricePredictionDatum { get; set; }

    public virtual DbSet<QuantmetricsT1datum> QuantmetricsT1datum { get; set; }

    public virtual DbSet<QuantmetricsT2datum> QuantmetricsT2datum { get; set; }

    public virtual DbSet<ResistanceSupportDatum> ResistanceSupportDatum { get; set; }

    public virtual DbSet<SentimentsDatum> SentimentsDatum { get; set; }

    public virtual DbSet<Tokens> Tokens { get; set; }

    public virtual DbSet<TraderGradesDatum> TraderGradesDatum { get; set; }

    public virtual DbSet<TradingIndicatorDatum> TradingIndicatorDatum { get; set; }

    protected override void OnModelCreating(ModelBuilder modelBuilder)
    {
            modelBuilder.ApplyConfiguration(new Configurations.CorrelationDatumConfiguration());
            modelBuilder.ApplyConfiguration(new Configurations.IndiciesDatumConfiguration());
            modelBuilder.ApplyConfiguration(new Configurations.PricePredictionDatumConfiguration());
            modelBuilder.ApplyConfiguration(new Configurations.QuantmetricsT1datumConfiguration());
            modelBuilder.ApplyConfiguration(new Configurations.QuantmetricsT2datumConfiguration());
            modelBuilder.ApplyConfiguration(new Configurations.ResistanceSupportDatumConfiguration());
            modelBuilder.ApplyConfiguration(new Configurations.SentimentsDatumConfiguration());
            modelBuilder.ApplyConfiguration(new Configurations.TokensConfiguration());
            modelBuilder.ApplyConfiguration(new Configurations.TraderGradesDatumConfiguration());
            modelBuilder.ApplyConfiguration(new Configurations.TradingIndicatorDatumConfiguration());

        OnModelCreatingPartial(modelBuilder);
    }

    partial void OnModelCreatingPartial(ModelBuilder modelBuilder);
}
