// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace TradeMonkey.Data.Entity;

public partial class Correlation_Datum
{
    public int Id { get; set; }

    public double Correlation { get; set; }

    public DateTime Date { get; set; }

    public string Token_2_Name { get; set; }

    public int? Token_2_Symbol { get; set; }

    public long? Epoch { get; set; }
}