// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace TradeMonkey.Data.Entity;

public partial class CorrelationDatum
{
    public int TokenId { get; set; }

    public double Correlation { get; set; }

    public DateTime Date { get; set; }

    public string Token2Name { get; set; }

    public int? Token2Symbol { get; set; }

    public long? Epoch { get; set; }
}