// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace TradeMonkey.Data.Entity;

public partial class CryptoData
{
    public int Id { get; set; }

    public DateTime? TimePeriodStart { get; set; }

    public DateTime? TimePeriodEnd { get; set; }

    public DateTime? TimeOpen { get; set; }

    public DateTime? TimeClose { get; set; }

    public decimal? RateOpen { get; set; }

    public decimal? RateHigh { get; set; }

    public decimal? RateLow { get; set; }

    public decimal? RateClose { get; set; }
}