// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace TradeMonkey.Data.Entity;

public partial class IndicatorDatum
{
    public int TokenId { get; set; }

    public int Epoch { get; set; }

    public int LastTmGradeSignal { get; set; }

    public double TmGradePercHighCoins { get; set; }

    public int TmGradeSignal { get; set; }

    public double TotalCryptoMcap { get; set; }
}