// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace TradeMonkey.Data.Entity;

public partial class IndiciesDatum
{
    public int Id { get; set; }

    public int BL_Weight { get; set; }

    public DateTime? Date { get; set; }
}