// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace TradeMonkey.Data.Entity;

public partial class IndiciesDatum
{
    public int TokenId { get; set; }

    public int BlWeight { get; set; }

    public DateOnly? Date { get; set; }
}