// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace TradeMonkey.Data.Entity;

public partial class Kucoin_Account
{
    public int Id { get; set; }

    public string currency { get; set; }

    public string type { get; set; }

    public decimal balance { get; set; }

    public decimal available { get; set; }

    public int holds { get; set; }

    public DateTime Updated { get; set; }
}