// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace TradeMonkey.Data.Entity;

public partial class KucoinHistory
{
    public int Unix { get; set; }

    public DateTime Date { get; set; }

    public string Symbol { get; set; }

    public double Open { get; set; }

    public double High { get; set; }

    public double Low { get; set; }

    public double Close { get; set; }

    public double Volume1inch { get; set; }

    public double VolumeUsdt { get; set; }
}