// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace TradeMonkey.Data.Entity;

public partial class Kucoin24hourStats
{
    public string Symbol { get; set; }

    public decimal? HighPrice { get; set; }

    public decimal? LowPrice { get; set; }

    public decimal? Volume { get; set; }

    public decimal? QuoteVolume { get; set; }

    public decimal? LastPrice { get; set; }

    public decimal? BestAskPrice { get; set; }

    public decimal? BestBidPrice { get; set; }

    public decimal? ChangePrice { get; set; }

    public decimal? ChangePercentage { get; set; }

    public DateTime Timestamp { get; set; }

    public decimal? AveragePrice { get; set; }

    public decimal? TakerFeeRate { get; set; }

    public decimal? MakerFeeRate { get; set; }

    public decimal? TakerCoefficient { get; set; }

    public decimal? MakerCoefficient { get; set; }
}