// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace TradeMonkey.Data.Entity;

public partial class KucoinAccounts
{
    public string Id { get; set; }

    public string Asset { get; set; }

    public int Type { get; set; }

    public decimal Total { get; set; }

    public decimal Available { get; set; }

    public decimal Holds { get; set; }
}