// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace TradeMonkey.Data.Entity;

public partial class KucoinKline
{
    public int Id { get; set; }

    public DateTime OpenTime { get; set; }

    public decimal OpenPrice { get; set; }

    public decimal ClosePrice { get; set; }

    public decimal HighPrice { get; set; }

    public decimal LowPrice { get; set; }

    public decimal Volume { get; set; }

    public decimal QuoteVolume { get; set; }
}