// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace TradeMonkey.Data.Entity;

public partial class KucoinIsolatedMarginAccountsInfo
{
    public decimal TotalConversionBalance { get; set; }

    public decimal LiabilityConversionBalance { get; set; }
}