// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace TradeMonkey.Data.Entity;

public partial class KucoinTickerHistories
{
    public int unix { get; set; }

    public DateTime date { get; set; }

    public string symbol { get; set; }

    public double open { get; set; }

    public double high { get; set; }

    public double low { get; set; }

    public double close { get; set; }

    public double Volume_ADA { get; set; }

    public double Volume_USDT { get; set; }

    public string Time_Frame { get; set; }
}