// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace TradeMonkey.Data.Entity;

public partial class Kucoin_AllTick
{
    public int Id { get; set; }

    public string symbol { get; set; }

    public string symbolName { get; set; }

    public double buy { get; set; }

    public double sell { get; set; }

    public double changeRate { get; set; }

    public double changePrice { get; set; }

    public double high { get; set; }

    public double low { get; set; }

    public double vol { get; set; }

    public double volValue { get; set; }

    public double last { get; set; }

    public double averagePrice { get; set; }

    public double takerFeeRate { get; set; }

    public double makerFeeRate { get; set; }

    public double takerCoefficient { get; set; }

    public double makerCoefficient { get; set; }

    public DateTime timestamp { get; set; }
}