// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace TradeMonkey.Data.Entity;

public partial class KucoinAllTick
{
    public int Id { get; set; }

    public string Symbol { get; set; }

    public string SymbolName { get; set; }

    public double Buy { get; set; }

    public double Sell { get; set; }

    public double ChangeRate { get; set; }

    public double ChangePrice { get; set; }

    public double High { get; set; }

    public double Low { get; set; }

    public double Vol { get; set; }

    public double VolValue { get; set; }

    public double Last { get; set; }

    public double AveragePrice { get; set; }

    public double TakerFeeRate { get; set; }

    public double MakerFeeRate { get; set; }

    public double TakerCoefficient { get; set; }

    public double MakerCoefficient { get; set; }

    public DateTime Timestamp { get; set; }
}