// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace TradeMonkey.Data.Entity;

public partial class KucoinTokenMetricsSymbol
{
    public int Id { get; set; }

    public string KucoinSymbol { get; set; }

    public string TokenMetricsSymbol { get; set; }

    public bool Trade { get; set; }
}