// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace TradeMonkey.Data.Entity;

public partial class KucoinIsolatedMarginAccounts
{
    public string Symbol { get; set; }

    public int Status { get; set; }

    public decimal DebtRatio { get; set; }

    public string BaseAsset_Currency { get; set; }

    public decimal BaseAsset_TotalBalance { get; set; }

    public decimal BaseAsset_HoldBalance { get; set; }

    public decimal BaseAsset_AvailableBalance { get; set; }

    public decimal BaseAsset_Liability { get; set; }

    public decimal BaseAsset_Interest { get; set; }

    public decimal BaseAsset_BorrowableQuantity { get; set; }

    public string QuoteAsset_Currency { get; set; }

    public decimal QuoteAsset_TotalBalance { get; set; }

    public decimal QuoteAsset_HoldBalance { get; set; }

    public decimal QuoteAsset_AvailableBalance { get; set; }

    public decimal QuoteAsset_Liability { get; set; }

    public decimal QuoteAsset_Interest { get; set; }

    public decimal QuoteAsset_BorrowableQuantity { get; set; }
}