// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace TradeMonkey.Data.Entity;

public partial class PricePredictionDatum
{
    public int TokenId { get; set; }

    public double Close { get; set; }

    public int Epoch { get; set; }

    public double High { get; set; }

    public double Low { get; set; }

    public string Name { get; set; }

    public double Open { get; set; }

    public string Symbol { get; set; }

    public int TokenId1 { get; set; }

    public double Volume { get; set; }
}