// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace TradeMonkey.Data.Entity;

public partial class QuantmetricsT1_Datum
{
    public int Id { get; set; }

    public double Beta { get; set; }

    public double Cagr { get; set; }

    public double CumulativeReturn { get; set; }

    public string Date { get; set; }

    public int EndPeriod { get; set; }

    public int Epoch { get; set; }

    public double MaxDrawdown { get; set; }

    public string Name { get; set; }

    public double Sharpe { get; set; }

    public double Sortino { get; set; }

    public int StartPeriod { get; set; }

    public string Symbol { get; set; }

    public int TokenId { get; set; }

    public double Volatility { get; set; }

    public virtual TokenMetrics_Token Token { get; set; }
}