// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace TradeMonkey.Data.Entity;

public partial class QuantmetricsT2datum
{
    public int Id { get; set; }

    public double AvgDailyReturn { get; set; }

    public double AvgDownMonth { get; set; }

    public double AvgMontlyReturn { get; set; }

    public double AvgUpMonth { get; set; }

    public double BestDay { get; set; }

    public double BestMonth { get; set; }

    public string Date { get; set; }

    public int EndPeriod { get; set; }

    public int Epoch { get; set; }

    public double MaxDailyReturn { get; set; }

    public double MaxMonthlyReturn { get; set; }

    public double MinDailyReturn { get; set; }

    public double MinMonthlyReturn { get; set; }

    public string Name { get; set; }

    public int StartPeriod { get; set; }

    public double StdDailyReturn { get; set; }

    public double StdMonthlyReturn { get; set; }

    public string Symbol { get; set; }

    public int Token_Id { get; set; }

    public double WorstDay { get; set; }

    public double WorstMonth { get; set; }

    public virtual Tokens Token { get; set; }
}