// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace TradeMonkey.Data.Entity;

public partial class ResistanceSupportDatum
{
    public int Id { get; set; }

    public int Epoch { get; set; }

    public int Level { get; set; }

    public string TokenId { get; set; }
}