// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace TradeMonkey.Data.Entity;

public partial class ScenarioAnalysisDatum
{
    public int TokenId { get; set; }

    public double CurrentDominance { get; set; }

    public string Date { get; set; }

    public double Dominance { get; set; }

    public int Epoch { get; set; }

    public string Name { get; set; }

    public double Prediction { get; set; }

    public string Symbol { get; set; }

    public int TokenId1 { get; set; }

    public double TotalMarketCap { get; set; }
}