// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace TradeMonkey.Data.Entity;

public partial class SentimentsDatum
{
    public string Date { get; set; }

    public int Epoch { get; set; }

    public string Name { get; set; }

    public string PolarityReddit { get; set; }

    public double PolarityIndex { get; set; }

    public string PolarityTelegram { get; set; }

    public double PolarityTwitter { get; set; }

    public string SentimentIndex { get; set; }

    public string Symbol { get; set; }

    public int Token_Id { get; set; }

    public virtual Tokens Token { get; set; }
}