// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace TradeMonkey.Data.Entity;

public partial class TokenMetricsResSuppDatum
{
    public int TokenId { get; set; }

    public long Epoch { get; set; }

    public decimal? Level { get; set; }

    public DateTime DateCreated { get; set; }
}