// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace TradeMonkey.Data.Entity;

public partial class TokenMetrics_Token
{
    public int Token_Id { get; set; }

    public string Name { get; set; }

    public string Symbol { get; set; }

    public virtual ICollection<PricePrediction_Datum> PricePrediction_Datum { get; } = new List<PricePrediction_Datum>();

    public virtual ICollection<QuantmetricsT1_Datum> QuantmetricsT1_Datum { get; } = new List<QuantmetricsT1_Datum>();

    public virtual ICollection<QuantmetricsT2_Datum> QuantmetricsT2_Datum { get; } = new List<QuantmetricsT2_Datum>();

    public virtual ICollection<ScenarioAnalysis_Datum> ScenarioAnalysis_Datum { get; } = new List<ScenarioAnalysis_Datum>();

    public virtual ICollection<Sentiments_Datum> Sentiments_Datum { get; } = new List<Sentiments_Datum>();

    public virtual ICollection<TradingIndicato_rDatum> TradingIndicato_rDatum { get; } = new List<TradingIndicato_rDatum>();
}