// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace TradeMonkey.Data.Entity;

public partial class Tokens
{
    public int Token_Id { get; set; }

    public string Name { get; set; }

    public string Symbol { get; set; }

    public virtual ICollection<PricePredictionDatum> PricePredictionDatum { get; } = new List<PricePredictionDatum>();

    public virtual ICollection<QuantmetricsT1Datum> QuantmetricsT1Datum { get; } = new List<QuantmetricsT1Datum>();

    public virtual ICollection<QuantmetricsT2Datum> QuantmetricsT2Datum { get; } = new List<QuantmetricsT2Datum>();

    public virtual ICollection<ScenarioAnalysisDatum> ScenarioAnalysisDatum { get; } = new List<ScenarioAnalysisDatum>();

    public virtual ICollection<SentimentsDatum> SentimentsDatum { get; } = new List<SentimentsDatum>();

    public virtual ICollection<TradingIndicatorDatum> TradingIndicatorDatum { get; } = new List<TradingIndicatorDatum>();
}