// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace TradeMonkey.Data.Entity;

public partial class Token
{
    public string Name { get; set; }

    public string Symbol { get; set; }

    public int TokenId { get; set; }
}