// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.Text.Json.Serialization;

namespace TradeMonkey.Data.Entity;

public partial class TradingIndicatorDatum
{
    [JsonPropertyName("tokenId")]
    public int Token_Id { get; set; }

    [JsonPropertyName("close")]
    public double Close { get; set; }

    [JsonPropertyName("date")]
    public string Date { get; set; }

    [JsonPropertyName("epoch")]
    public int Epoch { get; set; }

    [JsonPropertyName("holdingCumulativeRoi")]
    public double? HoldingCumulativeRoi { get; set; }

    [JsonPropertyName("lastSignal")]
    public int LastSignal { get; set; }

    [JsonPropertyName("name")]
    public string Name { get; set; }

    [JsonPropertyName("signal")]
    public int Signal { get; set; }

    [JsonPropertyName("strategyCummulativeRoi")]
    public double? StrategyCummulativeRoi { get; set; }

    [JsonPropertyName("symbol")]
    public string Symbol { get; set; }

    [JsonPropertyName("tokenId")]
    public int TokenId { get; set; }

    [JsonPropertyName("volume")]
    public double Volume { get; set; }
}
