// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace TradeMonkey.Data.Entity;

public partial class TraderGradesDatum
{
    public int Id { get; set; }

    public string Date { get; set; }

    public int Epoch { get; set; }

    public string Name { get; set; }

    public double QuantGrade { get; set; }

    public string Symbol { get; set; }

    public double TaGrade { get; set; }

    public string TmTraderGrade { get; set; }

    public string TokenId { get; set; }
}