// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Metadata.Builders;
using System;
using System.Collections.Generic;
using TradeMonkey.Data.Context;
using TradeMonkey.Data.Entity;

namespace TradeMonkey.Data.Context.Configurations
{
    public partial class KucoinAccountConfiguration : IEntityTypeConfiguration<KucoinAccount>
    {
        public void Configure(EntityTypeBuilder<KucoinAccount> entity)
        {
            entity.HasKey(e => e.Id).HasName("PK_KucoinAccount");

            entity.ToTable("Kucoin_Accounts");

            entity.Property(e => e.Available)
            .HasDefaultValueSql("((0.00))")
            .HasColumnType("decimal(18, 0)")
            .HasColumnName("available");
            entity.Property(e => e.Balance)
            .HasDefaultValueSql("((0.00))")
            .HasColumnType("decimal(18, 0)")
            .HasColumnName("balance");
            entity.Property(e => e.Currency)
            .IsRequired()
            .HasMaxLength(10)
            .IsUnicode(false)
            .HasColumnName("currency");
            entity.Property(e => e.Holds).HasColumnName("holds");
            entity.Property(e => e.Type)
            .IsRequired()
            .HasMaxLength(10)
            .IsUnicode(false)
            .HasColumnName("type");
            entity.Property(e => e.Updated)
            .HasDefaultValueSql("(getdate())")
            .HasColumnType("datetime");

            OnConfigurePartial(entity);
        }

        partial void OnConfigurePartial(EntityTypeBuilder<KucoinAccount> entity);
    }
}
