// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Metadata.Builders;
using System;
using System.Collections.Generic;
using TradeMonkey.Data.Context;
using TradeMonkey.Data.Entity;

namespace TradeMonkey.Data.Context.Configurations
{
    public partial class KucoinIsolatedMarginAccountsInfoConfiguration : IEntityTypeConfiguration<KucoinIsolatedMarginAccountsInfo>
    {
        public void Configure(EntityTypeBuilder<KucoinIsolatedMarginAccountsInfo> entity)
        {
            entity.HasKey(e => new { e.TotalConversionBalance, e.LiabilityConversionBalance }).HasName("PK__KucoinIs__A35B0634C90E8F5E");

            entity.Property(e => e.TotalConversionBalance).HasColumnType("decimal(18, 8)");
            entity.Property(e => e.LiabilityConversionBalance).HasColumnType("decimal(18, 8)");

            OnConfigurePartial(entity);
        }

        partial void OnConfigurePartial(EntityTypeBuilder<KucoinIsolatedMarginAccountsInfo> entity);
    }
}
