// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Metadata.Builders;
using System;
using System.Collections.Generic;
using TradeMonkey.Data.Context;
using TradeMonkey.Data.Entity;

namespace TradeMonkey.Data.Context.Configurations
{
    public partial class KucoinKlinesConfiguration : IEntityTypeConfiguration<KucoinKlines>
    {
        public void Configure(EntityTypeBuilder<KucoinKlines> entity)
        {
            entity.HasKey(e => e.OpenTime).HasName("PK__KucoinKl__0D93B126B55BE71A");

            entity.HasIndex(e => e.HighPrice, "IX_KucoinKlines_HighPrice");

            entity.HasIndex(e => e.LowPrice, "IX_KucoinKlines_LowPrice");

            entity.Property(e => e.OpenTime).HasColumnType("datetime");
            entity.Property(e => e.ClosePrice).HasColumnType("decimal(18, 8)");
            entity.Property(e => e.HighPrice).HasColumnType("decimal(18, 8)");
            entity.Property(e => e.LowPrice).HasColumnType("decimal(18, 8)");
            entity.Property(e => e.OpenPrice).HasColumnType("decimal(18, 8)");
            entity.Property(e => e.QuoteVolume).HasColumnType("decimal(18, 8)");
            entity.Property(e => e.Volume).HasColumnType("decimal(18, 8)");

            OnConfigurePartial(entity);
        }

        partial void OnConfigurePartial(EntityTypeBuilder<KucoinKlines> entity);
    }
}
