// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Metadata.Builders;
using System;
using System.Collections.Generic;
using TradeMonkey.Data.Context;
using TradeMonkey.Data.Entity;

namespace TradeMonkey.Data.Context.Configurations
{
    public partial class KucoinIsolatedMarginAccountsConfiguration : IEntityTypeConfiguration<KucoinIsolatedMarginAccounts>
    {
        public void Configure(EntityTypeBuilder<KucoinIsolatedMarginAccounts> entity)
        {
            entity.HasKey(e => e.Symbol).HasName("PK__KucoinIs__B7CC3F00BCA7E62F");

            entity.HasIndex(e => e.Status, "IX_KucoinIsolatedMarginAccounts_Status");

            entity.Property(e => e.Symbol)
            .HasMaxLength(20)
            .IsUnicode(false);
            entity.Property(e => e.BaseAsset_AvailableBalance).HasColumnType("decimal(18, 8)");
            entity.Property(e => e.BaseAsset_BorrowableQuantity).HasColumnType("decimal(18, 8)");
            entity.Property(e => e.BaseAsset_Currency)
            .IsRequired()
            .HasMaxLength(20)
            .IsUnicode(false);
            entity.Property(e => e.BaseAsset_HoldBalance).HasColumnType("decimal(18, 8)");
            entity.Property(e => e.BaseAsset_Interest).HasColumnType("decimal(18, 8)");
            entity.Property(e => e.BaseAsset_Liability).HasColumnType("decimal(18, 8)");
            entity.Property(e => e.BaseAsset_TotalBalance).HasColumnType("decimal(18, 8)");
            entity.Property(e => e.DebtRatio).HasColumnType("decimal(18, 8)");
            entity.Property(e => e.QuoteAsset_AvailableBalance).HasColumnType("decimal(18, 8)");
            entity.Property(e => e.QuoteAsset_BorrowableQuantity).HasColumnType("decimal(18, 8)");
            entity.Property(e => e.QuoteAsset_Currency)
            .IsRequired()
            .HasMaxLength(20)
            .IsUnicode(false);
            entity.Property(e => e.QuoteAsset_HoldBalance).HasColumnType("decimal(18, 8)");
            entity.Property(e => e.QuoteAsset_Interest).HasColumnType("decimal(18, 8)");
            entity.Property(e => e.QuoteAsset_Liability).HasColumnType("decimal(18, 8)");
            entity.Property(e => e.QuoteAsset_TotalBalance).HasColumnType("decimal(18, 8)");

            OnConfigurePartial(entity);
        }

        partial void OnConfigurePartial(EntityTypeBuilder<KucoinIsolatedMarginAccounts> entity);
    }
}
