// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Metadata.Builders;
using System;
using System.Collections.Generic;
using TradeMonkey.Data.Context;
using TradeMonkey.Data.Entity;

namespace TradeMonkey.Data.Context.Configurations
{
    public partial class Kucoin24hourStatsConfiguration : IEntityTypeConfiguration<Kucoin24hourStats>
    {
        public void Configure(EntityTypeBuilder<Kucoin24hourStats> entity)
        {
            entity.HasKey(e => new { e.Symbol, e.Timestamp }).HasName("PK_Kucoin24HourStat");

            entity.ToTable("Kucoin_24HourStats");

            entity.Property(e => e.Symbol)
            .HasMaxLength(20)
            .IsUnicode(false);
            entity.Property(e => e.AveragePrice).HasColumnType("decimal(18, 9)");
            entity.Property(e => e.BestAskPrice).HasColumnType("decimal(18, 9)");
            entity.Property(e => e.BestBidPrice).HasColumnType("decimal(18, 9)");
            entity.Property(e => e.ChangePercentage).HasColumnType("decimal(18, 9)");
            entity.Property(e => e.ChangePrice).HasColumnType("decimal(18, 9)");
            entity.Property(e => e.HighPrice).HasColumnType("decimal(18, 9)");
            entity.Property(e => e.LastPrice).HasColumnType("decimal(18, 9)");
            entity.Property(e => e.LowPrice).HasColumnType("decimal(18, 9)");
            entity.Property(e => e.MakerCoefficient).HasColumnType("decimal(18, 9)");
            entity.Property(e => e.MakerFeeRate).HasColumnType("decimal(18, 9)");
            entity.Property(e => e.QuoteVolume).HasColumnType("decimal(18, 9)");
            entity.Property(e => e.TakerCoefficient).HasColumnType("decimal(18, 9)");
            entity.Property(e => e.TakerFeeRate).HasColumnType("decimal(18, 9)");
            entity.Property(e => e.Volume).HasColumnType("decimal(18, 9)");

            OnConfigurePartial(entity);
        }

        partial void OnConfigurePartial(EntityTypeBuilder<Kucoin24hourStats> entity);
    }
}
