// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Metadata.Builders;
using System;
using System.Collections.Generic;
using TradeMonkey.Data.Context;
using TradeMonkey.Data.Entity;

namespace TradeMonkey.Data.Context.Configurations
{
    public partial class KucoinKlineConfiguration : IEntityTypeConfiguration<KucoinKline>
    {
        public void Configure(EntityTypeBuilder<KucoinKline> entity)
        {
            entity.HasKey(e => e.Id).HasName("PK__KucoinKl__3214EC0748AD298D");

            entity.ToTable("KucoinKline");

            entity.Property(e => e.ClosePrice).HasColumnType("decimal(18, 8)");
            entity.Property(e => e.HighPrice).HasColumnType("decimal(18, 8)");
            entity.Property(e => e.LowPrice).HasColumnType("decimal(18, 8)");
            entity.Property(e => e.OpenPrice).HasColumnType("decimal(18, 8)");
            entity.Property(e => e.OpenTime).HasColumnType("datetime");
            entity.Property(e => e.QuoteVolume).HasColumnType("decimal(18, 8)");
            entity.Property(e => e.Volume).HasColumnType("decimal(18, 8)");

            OnConfigurePartial(entity);
        }

        partial void OnConfigurePartial(EntityTypeBuilder<KucoinKline> entity);
    }
}
