// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Metadata.Builders;
using System;
using System.Collections.Generic;
using TradeMonkey.Data.Context;
using TradeMonkey.Data.Entity;

namespace TradeMonkey.Data.Context.Configurations
{
    public partial class KucoinHistoryConfiguration : IEntityTypeConfiguration<KucoinHistory>
    {
        public void Configure(EntityTypeBuilder<KucoinHistory> entity)
        {
            entity.HasKey(e => new { e.Date, e.Symbol });

            entity.ToTable("Kucoin_History");

            entity.Property(e => e.Date).HasColumnName("date");
            entity.Property(e => e.Symbol)
            .HasMaxLength(50)
            .HasColumnName("symbol");
            entity.Property(e => e.Close).HasColumnName("close");
            entity.Property(e => e.High).HasColumnName("high");
            entity.Property(e => e.Low).HasColumnName("low");
            entity.Property(e => e.Open).HasColumnName("open");
            entity.Property(e => e.Unix).HasColumnName("unix");
            entity.Property(e => e.Volume1inch).HasColumnName("Volume_1INCH");
            entity.Property(e => e.VolumeUsdt).HasColumnName("Volume_USDT");

            OnConfigurePartial(entity);
        }

        partial void OnConfigurePartial(EntityTypeBuilder<KucoinHistory> entity);
    }
}
