// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Metadata.Builders;
using System;
using System.Collections.Generic;
using TradeMonkey.Data.Context;
using TradeMonkey.Data.Entity;

namespace TradeMonkey.Data.Context.Configurations
{
    public partial class KucoinAllTickConfiguration : IEntityTypeConfiguration<KucoinAllTick>
    {
        public void Configure(EntityTypeBuilder<KucoinAllTick> entity)
        {
            entity.HasKey(e => e.Id).HasName("PK_KucoinTicker");

            entity.ToTable("Kucoin_AllTicks");

            entity.Property(e => e.AveragePrice).HasColumnName("averagePrice");
            entity.Property(e => e.Buy).HasColumnName("buy");
            entity.Property(e => e.ChangePrice).HasColumnName("changePrice");
            entity.Property(e => e.ChangeRate).HasColumnName("changeRate");
            entity.Property(e => e.High).HasColumnName("high");
            entity.Property(e => e.Last).HasColumnName("last");
            entity.Property(e => e.Low).HasColumnName("low");
            entity.Property(e => e.MakerCoefficient).HasColumnName("makerCoefficient");
            entity.Property(e => e.MakerFeeRate).HasColumnName("makerFeeRate");
            entity.Property(e => e.Sell).HasColumnName("sell");
            entity.Property(e => e.Symbol)
            .IsRequired()
            .HasMaxLength(20)
            .HasColumnName("symbol");
            entity.Property(e => e.SymbolName)
            .IsRequired()
            .HasMaxLength(20)
            .HasColumnName("symbolName");
            entity.Property(e => e.TakerCoefficient).HasColumnName("takerCoefficient");
            entity.Property(e => e.TakerFeeRate).HasColumnName("takerFeeRate");
            entity.Property(e => e.Timestamp)
            .HasColumnType("datetime")
            .HasColumnName("timestamp");
            entity.Property(e => e.Vol).HasColumnName("vol");
            entity.Property(e => e.VolValue).HasColumnName("volValue");

            OnConfigurePartial(entity);
        }

        partial void OnConfigurePartial(EntityTypeBuilder<KucoinAllTick> entity);
    }
}
