// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Metadata.Builders;
using System;
using System.Collections.Generic;
using TradeMonkey.Data.Context;
using TradeMonkey.Data.Entity;

namespace TradeMonkey.Data.Context.Configurations
{
    public partial class Kucoin_AllTickConfiguration : IEntityTypeConfiguration<Kucoin_AllTick>
    {
        public void Configure(EntityTypeBuilder<Kucoin_AllTick> entity)
        {
            entity.HasKey(e => e.Id).HasName("PK_KucoinTicker");

            entity.Property(e => e.symbol)
            .IsRequired()
            .HasMaxLength(20);
            entity.Property(e => e.symbolName)
            .IsRequired()
            .HasMaxLength(20);
            entity.Property(e => e.timestamp).HasColumnType("datetime");

            OnConfigurePartial(entity);
        }

        partial void OnConfigurePartial(EntityTypeBuilder<Kucoin_AllTick> entity);
    }
}
