// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Metadata.Builders;
using System;
using System.Collections.Generic;
using TradeMonkey.Data.Context;
using TradeMonkey.Data.Entity;

namespace TradeMonkey.Data.Context.Configurations
{
    public partial class Kucoin_AccountConfiguration : IEntityTypeConfiguration<Kucoin_Account>
    {
        public void Configure(EntityTypeBuilder<Kucoin_Account> entity)
        {
            entity.HasKey(e => e.Id).HasName("PK_KucoinAccount");

            entity.Property(e => e.Updated)
            .HasDefaultValueSql("(getdate())")
            .HasColumnType("datetime");
            entity.Property(e => e.available)
            .HasDefaultValueSql("((0.00))")
            .HasColumnType("decimal(18, 0)");
            entity.Property(e => e.balance)
            .HasDefaultValueSql("((0.00))")
            .HasColumnType("decimal(18, 0)");
            entity.Property(e => e.currency)
            .IsRequired()
            .HasMaxLength(10)
            .IsUnicode(false);
            entity.Property(e => e.type)
            .IsRequired()
            .HasMaxLength(10)
            .IsUnicode(false);

            OnConfigurePartial(entity);
        }

        partial void OnConfigurePartial(EntityTypeBuilder<Kucoin_Account> entity);
    }
}
