// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Metadata.Builders;
using System;
using System.Collections.Generic;
using TradeMonkey.Data.Context;
using TradeMonkey.Data.Entity;

namespace TradeMonkey.Data.Context.Configurations
{
    public partial class KucoinTokenMetricsSymbolConfiguration : IEntityTypeConfiguration<KucoinTokenMetricsSymbol>
    {
        public void Configure(EntityTypeBuilder<KucoinTokenMetricsSymbol> entity)
        {
            entity.Property(e => e.KucoinSymbol)
            .IsRequired()
            .HasMaxLength(50)
            .IsUnicode(false);
            entity.Property(e => e.TokenMetricsSymbol)
            .IsRequired()
            .HasMaxLength(50)
            .IsUnicode(false);

            OnConfigurePartial(entity);
        }

        partial void OnConfigurePartial(EntityTypeBuilder<KucoinTokenMetricsSymbol> entity);
    }
}
