// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Metadata.Builders;
using System;
using System.Collections.Generic;
using TradeMonkey.Data.Context;
using TradeMonkey.Data.Entity;

namespace TradeMonkey.Data.Context.Configurations
{
    public partial class KucoinAccountsConfiguration : IEntityTypeConfiguration<KucoinAccounts>
    {
        public void Configure(EntityTypeBuilder<KucoinAccounts> entity)
        {
            entity.HasKey(e => e.Id).HasName("PK__KucoinAc__3214EC07BCC0C342");

            entity.HasIndex(e => e.Asset, "IX_KucoinAccounts_Asset");

            entity.Property(e => e.Id)
            .HasMaxLength(50)
            .IsUnicode(false);
            entity.Property(e => e.Asset)
            .IsRequired()
            .HasMaxLength(20)
            .IsUnicode(false);
            entity.Property(e => e.Available).HasColumnType("decimal(18, 8)");
            entity.Property(e => e.Holds).HasColumnType("decimal(18, 8)");
            entity.Property(e => e.Total).HasColumnType("decimal(18, 8)");

            OnConfigurePartial(entity);
        }

        partial void OnConfigurePartial(EntityTypeBuilder<KucoinAccounts> entity);
    }
}
