// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Metadata.Builders;
using System;
using System.Collections.Generic;
using TradeMonkey.Data.Context;
using TradeMonkey.Data.Entity;

namespace TradeMonkey.Data.Context.Configurations
{
    public partial class PricePrediction_DatumConfiguration : IEntityTypeConfiguration<PricePrediction_Datum>
    {
        public void Configure(EntityTypeBuilder<PricePrediction_Datum> entity)
        {
            entity.HasKey(e => e.Id).HasName("PK_PricePredictionDatum");

            entity.Property(e => e.Name)
            .IsRequired()
            .HasMaxLength(255)
            .IsUnicode(false);
            entity.Property(e => e.Symbol)
            .IsRequired()
            .HasMaxLength(255)
            .IsUnicode(false);

            entity.HasOne(d => d.Token).WithMany(p => p.PricePrediction_Datum)
            .HasForeignKey(d => d.TokenId)
            .OnDelete(DeleteBehavior.ClientSetNull)
            .HasConstraintName("FK_PricePredictionDatum_Tokens");

            OnConfigurePartial(entity);
        }

        partial void OnConfigurePartial(EntityTypeBuilder<PricePrediction_Datum> entity);
    }
}
