// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Metadata.Builders;
using System;
using System.Collections.Generic;
using TradeMonkey.Data.Context;
using TradeMonkey.Data.Entity;

namespace TradeMonkey.Data.Context.Configurations
{
    public partial class QuantmetricsT1DatumConfiguration : IEntityTypeConfiguration<QuantmetricsT1Datum>
    {
        public void Configure(EntityTypeBuilder<QuantmetricsT1Datum> entity)
        {
            entity.Property(e => e.Date)
            .IsRequired()
            .HasMaxLength(255)
            .IsUnicode(false);
            entity.Property(e => e.Name)
            .IsRequired()
            .HasMaxLength(255)
            .IsUnicode(false);
            entity.Property(e => e.Symbol)
            .IsRequired()
            .HasMaxLength(255)
            .IsUnicode(false);

            entity.HasOne(d => d.Token).WithMany(p => p.QuantmetricsT1Datum)
            .HasForeignKey(d => d.TokenId)
            .OnDelete(DeleteBehavior.ClientSetNull)
            .HasConstraintName("FK_QuantmetricsT1Datum_Tokens");

            OnConfigurePartial(entity);
        }

        partial void OnConfigurePartial(EntityTypeBuilder<QuantmetricsT1Datum> entity);
    }
}
