// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Metadata.Builders;
using System;
using System.Collections.Generic;
using TradeMonkey.Data.Context;
using TradeMonkey.Data.Entity;

namespace TradeMonkey.Data.Context.Configurations
{
    public partial class ScenarioAnalysisDatumConfiguration : IEntityTypeConfiguration<ScenarioAnalysisDatum>
    {
        public void Configure(EntityTypeBuilder<ScenarioAnalysisDatum> entity)
        {
            entity.HasKey(e => e.TokenId).HasName("PK_ScenarioAnalysisDatum");

            entity.ToTable("ScenarioAnalysis_Datums");

            entity.HasIndex(e => e.TokenId1, "IX_ScenarioAnalysis_Datums_TokenId");

            entity.Property(e => e.TokenId)
            .ValueGeneratedNever()
            .HasColumnName("Token_Id");
            entity.Property(e => e.Date)
            .IsRequired()
            .HasMaxLength(50)
            .IsUnicode(false);
            entity.Property(e => e.Name)
            .IsRequired()
            .HasMaxLength(50)
            .IsUnicode(false);
            entity.Property(e => e.Symbol)
            .IsRequired()
            .HasMaxLength(50)
            .IsUnicode(false);
            entity.Property(e => e.TokenId1).HasColumnName("TokenId");

            OnConfigurePartial(entity);
        }

        partial void OnConfigurePartial(EntityTypeBuilder<ScenarioAnalysisDatum> entity);
    }
}
