// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Metadata.Builders;
using System;
using System.Collections.Generic;
using TradeMonkey.Data.Context;
using TradeMonkey.Data.Entity;

namespace TradeMonkey.Data.Context.Configurations
{
    public partial class ScenarioAnalysis_DatumConfiguration : IEntityTypeConfiguration<ScenarioAnalysis_Datum>
    {
        public void Configure(EntityTypeBuilder<ScenarioAnalysis_Datum> entity)
        {
            entity.HasKey(e => e.Id).HasName("PK_ScenarioAnalysisDatum");

            entity.Property(e => e.Date)
            .IsRequired()
            .HasMaxLength(50)
            .IsUnicode(false);
            entity.Property(e => e.Name)
            .IsRequired()
            .HasMaxLength(50)
            .IsUnicode(false);
            entity.Property(e => e.Symbol)
            .IsRequired()
            .HasMaxLength(50)
            .IsUnicode(false);

            entity.HasOne(d => d.Token).WithMany(p => p.ScenarioAnalysis_Datum)
            .HasForeignKey(d => d.TokenId)
            .OnDelete(DeleteBehavior.ClientSetNull)
            .HasConstraintName("FK_ScenarioAnalysisDatum_Tokens");

            OnConfigurePartial(entity);
        }

        partial void OnConfigurePartial(EntityTypeBuilder<ScenarioAnalysis_Datum> entity);
    }
}
