// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Metadata.Builders;
using System;
using System.Collections.Generic;
using TradeMonkey.Data.Context;
using TradeMonkey.Data.Entity;

namespace TradeMonkey.Data.Context.Configurations
{
    public partial class Sentiments_DatumConfiguration : IEntityTypeConfiguration<Sentiments_Datum>
    {
        public void Configure(EntityTypeBuilder<Sentiments_Datum> entity)
        {
            entity.HasKey(e => new { e.Epoch, e.TokenId }).HasName("PK__Sentimen__BA902D88A91C6C0B");

            entity.Property(e => e.Date)
            .IsRequired()
            .HasMaxLength(50)
            .IsUnicode(false);
            entity.Property(e => e.Name)
            .IsRequired()
            .HasMaxLength(50)
            .IsUnicode(false);
            entity.Property(e => e.PolarityReddit)
            .HasMaxLength(50)
            .IsUnicode(false);
            entity.Property(e => e.PolarityTelegram)
            .HasMaxLength(50)
            .IsUnicode(false);
            entity.Property(e => e.SentimentIndex)
            .IsRequired()
            .HasMaxLength(50)
            .IsUnicode(false);
            entity.Property(e => e.Symbol)
            .IsRequired()
            .HasMaxLength(50)
            .IsUnicode(false);

            entity.HasOne(d => d.Token).WithMany(p => p.Sentiments_Datum)
            .HasForeignKey(d => d.TokenId)
            .OnDelete(DeleteBehavior.ClientSetNull)
            .HasConstraintName("FK_SentimentsDatum_Tokens");

            OnConfigurePartial(entity);
        }

        partial void OnConfigurePartial(EntityTypeBuilder<Sentiments_Datum> entity);
    }
}
