// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Metadata.Builders;
using System;
using System.Collections.Generic;
using TradeMonkey.Data.Context;
using TradeMonkey.Data.Entity;

namespace TradeMonkey.Data.Context.Configurations
{
    public partial class SentimentsDatumConfiguration : IEntityTypeConfiguration<SentimentsDatum>
    {
        public void Configure(EntityTypeBuilder<SentimentsDatum> entity)
        {
            entity.HasKey(e => e.TokenId);

            entity.ToTable("Sentiments_Datums");

            entity.HasIndex(e => e.TokenId, "IX_Sentiments_Datums_TokenId");

            entity.Property(e => e.TokenId)
            .ValueGeneratedNever()
            .HasColumnName("Token_Id");
            entity.Property(e => e.Date)
            .IsRequired()
            .HasMaxLength(50)
            .IsUnicode(false);
            entity.Property(e => e.Name)
            .IsRequired()
            .HasMaxLength(50)
            .IsUnicode(false);
            entity.Property(e => e.PolarityReddit)
            .HasMaxLength(50)
            .IsUnicode(false);
            entity.Property(e => e.PolarityTelegram)
            .HasMaxLength(50)
            .IsUnicode(false);
            entity.Property(e => e.SentimentIndex)
            .IsRequired()
            .HasMaxLength(50)
            .IsUnicode(false);
            entity.Property(e => e.Symbol)
            .IsRequired()
            .HasMaxLength(50)
            .IsUnicode(false);

            OnConfigurePartial(entity);
        }

        partial void OnConfigurePartial(EntityTypeBuilder<SentimentsDatum> entity);
    }
}
