// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Metadata.Builders;
using System;
using System.Collections.Generic;
using TradeMonkey.Data.Context;
using TradeMonkey.Data.Entity;

namespace TradeMonkey.Data.Context.Configurations
{
    public partial class TokenMetricsPriceConfiguration : IEntityTypeConfiguration<TokenMetricsPrice>
    {
        public void Configure(EntityTypeBuilder<TokenMetricsPrice> entity)
        {
            entity.HasKey(e => e.Id).HasName("PK__TokenMet__3214EC07D30134D8");

            entity.ToTable("TokenMetrics_Prices");

            entity.Property(e => e.Close).HasColumnType("decimal(18, 12)");
            entity.Property(e => e.CurrentPrice).HasColumnType("decimal(18, 12)");
            entity.Property(e => e.Date).HasColumnType("datetime");
            entity.Property(e => e.High).HasColumnType("decimal(18, 12)");
            entity.Property(e => e.Low).HasColumnType("decimal(18, 12)");
            entity.Property(e => e.Name)
            .IsRequired()
            .HasMaxLength(50)
            .IsUnicode(false);
            entity.Property(e => e.Open).HasColumnType("decimal(18, 12)");
            entity.Property(e => e.Symbol)
            .IsRequired()
            .HasMaxLength(10)
            .IsUnicode(false);
            entity.Property(e => e.Volume).HasColumnType("decimal(28, 8)");

            OnConfigurePartial(entity);
        }

        partial void OnConfigurePartial(EntityTypeBuilder<TokenMetricsPrice> entity);
    }
}
