// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Metadata.Builders;
using TradeMonkey.Data.Entity;

namespace TradeMonkey.Data.Context.Configurations
{
    public partial class TokensConfiguration : IEntityTypeConfiguration<Tokens>
    {
        public void Configure(EntityTypeBuilder<Tokens> entity)
        {
            entity.HasKey(e => e.TokenId);

            entity.Property(e => e.TokenId).ValueGeneratedNever();
            entity.Property(e => e.Name)
            .IsRequired()
            .HasMaxLength(20)
            .IsUnicode(false);

            OnConfigurePartial(entity);
        }

        partial void OnConfigurePartial(EntityTypeBuilder<Tokens> entity);
    }
}
