// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Metadata.Builders;
using System;
using System.Collections.Generic;
using TradeMonkey.Data.Context;
using TradeMonkey.Data.Entity;

namespace TradeMonkey.Data.Context.Configurations
{
    public partial class TradingIndicato_rDatumConfiguration : IEntityTypeConfiguration<TradingIndicato_rDatum>
    {
        public void Configure(EntityTypeBuilder<TradingIndicato_rDatum> entity)
        {
            entity.HasKey(e => e.Id).HasName("PK_TradingIndicatorDatum");

            entity.Property(e => e.Id).ValueGeneratedNever();
            entity.Property(e => e.Date)
            .IsRequired()
            .HasMaxLength(50)
            .IsUnicode(false);
            entity.Property(e => e.Name)
            .IsRequired()
            .HasMaxLength(50)
            .IsUnicode(false);
            entity.Property(e => e.Symbol)
            .IsRequired()
            .HasMaxLength(50)
            .IsUnicode(false);

            entity.HasOne(d => d.Token).WithMany(p => p.TradingIndicato_rDatum)
            .HasForeignKey(d => d.TokenId)
            .OnDelete(DeleteBehavior.ClientSetNull)
            .HasConstraintName("FK_TradingIndicatorDatum_Tokens");

            OnConfigurePartial(entity);
        }

        partial void OnConfigurePartial(EntityTypeBuilder<TradingIndicato_rDatum> entity);
    }
}
