// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Metadata.Builders;
using System;
using System.Collections.Generic;
using TradeMonkey.Data.Context;
using TradeMonkey.Data.Entity;

namespace TradeMonkey.Data.Context.Configurations
{
    public partial class TraderGradesDatumConfiguration : IEntityTypeConfiguration<TraderGradesDatum>
    {
        public void Configure(EntityTypeBuilder<TraderGradesDatum> entity)
        {
            entity.HasKey(e => e.Token_Id);

            entity.ToTable("TraderGrades_Datums");

            entity.Property(e => e.Token_Id)
            .ValueGeneratedNever()
            .HasColumnName("Token_Id");
            entity.Property(e => e.Date)
            .IsRequired()
            .HasMaxLength(50)
            .IsUnicode(false);
            entity.Property(e => e.Name)
            .IsRequired()
            .HasMaxLength(50)
            .IsUnicode(false);
            entity.Property(e => e.Symbol)
            .IsRequired()
            .HasMaxLength(50)
            .IsUnicode(false);
            entity.Property(e => e.TmTraderGrade)
            .IsRequired()
            .HasMaxLength(50)
            .IsUnicode(false);          

            OnConfigurePartial(entity);
        }

        partial void OnConfigurePartial(EntityTypeBuilder<TraderGradesDatum> entity);
    }
}
