// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Metadata.Builders;
using System;
using System.Collections.Generic;
using TradeMonkey.Data.Context;
using TradeMonkey.Data.Entity;

namespace TradeMonkey.Data.Context.Configurations
{
    public partial class TraderGradesDatumConfiguration : IEntityTypeConfiguration<TraderGradesDatum>
    {
        public void Configure(EntityTypeBuilder<TraderGradesDatum> entity)
        {
            entity.HasKey(e => e.Id).HasName("PK_TraderGrades_Datums_1");

            entity.ToTable("TraderGrades_Datums");

            entity.Property(e => e.Date)
            .IsRequired()
            .HasMaxLength(50)
            .IsUnicode(false);
            entity.Property(e => e.Name)
            .IsRequired()
            .HasMaxLength(50)
            .IsUnicode(false);
            entity.Property(e => e.QuantGrade).HasColumnType("decimal(18, 12)");
            entity.Property(e => e.Symbol)
            .IsRequired()
            .HasMaxLength(50)
            .IsUnicode(false);
            entity.Property(e => e.TaGrade).HasColumnType("decimal(18, 12)");
            entity.Property(e => e.TmTraderGrade).HasColumnType("decimal(18, 12)");
            entity.Property(e => e.TokenId).HasColumnName("Token_Id");

            OnConfigurePartial(entity);
        }

        partial void OnConfigurePartial(EntityTypeBuilder<TraderGradesDatum> entity);
    }
}
